### ISSUE TITLE
[Bug] compilation error with wayland-backend

### ISSUE THREAD

**Issue by werdahias** [Smithay/wayland-rs#605]
I'm trying to package the wayland-backend crate for debian. I patched it to use wayland-sys 0.29 and io-lifetimes 0.7.2. The build fails: 

```
   Compiling wayland-backend v0.1.1 (/<<PKGBUILDDIR>>)
     Running `CARGO=/usr/bin/cargo CARGO_CRATE_NAME=build_script_build CARGO_MANIFEST_DIR=/<<PKGBUILDDIR>> CARGO_PKG_AUTHORS='Elinor Berger <elinor@safaradeg.net>' CARGO_PKG_DESCRIPTION='Low-level bindings to the Wayland protocol' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=wayland-backend CARGO_PKG_REPOSITORY='https://github.com/smithay/wayland-rs' CARGO_PKG_RUST_VERSION=1.59 CARGO_PKG_VERSION=0.1.1 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=1 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/<<PKGBUILDDIR>>/target/debug/deps:/usr/lib' rustc --crate-name build_script_build --edition=2018 build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=9a4995da7f61ec8e -C extra-filename=-9a4995da7f61ec8e --out-dir /<<PKGBUILDDIR>>/target/debug/build/wayland-backend-9a4995da7f61ec8e -C incremental=/<<PKGBUILDDIR>>/target/debug/incremental -L dependency=/<<PKGBUILDDIR>>/target/debug/deps --extern cc=/<<PKGBUILDDIR>>/target/debug/deps/libcc-8e970e85c6220999.rlib`
     Running `/<<PKGBUILDDIR>>/target/debug/build/wayland-backend-9a4995da7f61ec8e/build-script-build`
   Compiling nix v0.26.1
     Running `CARGO=/usr/bin/cargo CARGO_CRATE_NAME=nix CARGO_MANIFEST_DIR=/<<PKGBUILDDIR>>/debian/cargo_registry/nix-0.26.1 CARGO_PKG_AUTHORS='The nix-rust Project Developers' CARGO_PKG_DESCRIPTION='Rust friendly bindings to *nix APIs' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=nix CARGO_PKG_REPOSITORY='https://github.com/nix-rust/nix' CARGO_PKG_RUST_VERSION=1.56 CARGO_PKG_VERSION=0.26.1 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=26 CARGO_PKG_VERSION_PATCH=1 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/<<PKGBUILDDIR>>/target/debug/deps:/usr/lib' rustc --crate-name nix --edition=2018 /<<PKGBUILDDIR>>/debian/cargo_registry/nix-0.26.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="event"' --cfg 'feature="fs"' --cfg 'feature="memoffset"' --cfg 'feature="poll"' --cfg 'feature="socket"' --cfg 'feature="uio"' -C metadata=d06b1ac03cad7931 -C extra-filename=-d06b1ac03cad7931 --out-dir /<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/<<PKGBUILDDIR>>/target/debug/deps --extern bitflags=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libbitflags-973a1f4f66d7af81.rmeta --extern cfg_if=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libcfg_if-eeaf0f0a0b47e76f.rmeta --extern libc=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-915f5cd4c3fac427.rmeta --extern memoffset=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libmemoffset-163e148a3d9e4ae6.rmeta --extern static_assertions=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libstatic_assertions-f75b061afb4b998f.rmeta --cap-lints warn -C debuginfo=2 --cap-lints warn -C linker=x86_64-linux-gnu-gcc -C link-arg=-Wl,-z,relro --remap-path-prefix /<<PKGBUILDDIR>>=/usr/share/cargo/registry/wayland-backend-0.1.1 --remap-path-prefix /<<PKGBUILDDIR>>/debian/cargo_registry=/usr/share/cargo/registry`
     Running `CARGO=/usr/bin/cargo CARGO_CRATE_NAME=io_lifetimes CARGO_MANIFEST_DIR=/<<PKGBUILDDIR>>/debian/cargo_registry/io-lifetimes-0.7.2 CARGO_PKG_AUTHORS='Dan Gohman <dev@sunfishcode.online>' CARGO_PKG_DESCRIPTION='A low-level I/O ownership and borrowing library' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE='Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT' CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=io-lifetimes CARGO_PKG_REPOSITORY='https://github.com/sunfishcode/io-lifetimes' CARGO_PKG_RUST_VERSION='' CARGO_PKG_VERSION=0.7.2 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=7 CARGO_PKG_VERSION_PATCH=2 CARGO_PKG_VERSION_PRE='' LD_LIBRARY_PATH='/<<PKGBUILDDIR>>/target/debug/deps:/usr/lib' OUT_DIR=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/build/io-lifetimes-e5f7cac95859834e/out rustc --crate-name io_lifetimes --edition=2018 /<<PKGBUILDDIR>>/debian/cargo_registry/io-lifetimes-0.7.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="close"' --cfg 'feature="default"' --cfg 'feature="libc"' -C metadata=229e7beedff98663 -C extra-filename=-229e7beedff98663 --out-dir /<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -L dependency=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/<<PKGBUILDDIR>>/target/debug/deps --extern libc=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/liblibc-915f5cd4c3fac427.rmeta --cap-lints warn -C debuginfo=2 --cap-lints warn -C linker=x86_64-linux-gnu-gcc -C link-arg=-Wl,-z,relro --remap-path-prefix /<<PKGBUILDDIR>>=/usr/share/cargo/registry/wayland-backend-0.1.1 --remap-path-prefix /<<PKGBUILDDIR>>/debian/cargo_registry=/usr/share/cargo/registry --cfg panic_in_const_fn`
     Running `CARGO=/usr/bin/cargo CARGO_CRATE_NAME=wayland_backend CARGO_MANIFEST_DIR=/<<PKGBUILDDIR>> CARGO_PKG_AUTHORS='Elinor Berger <elinor@safaradeg.net>' CARGO_PKG_DESCRIPTION='Low-level bindings to the Wayland protocol' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=wayland-backend CARGO_PKG_REPOSITORY='https://github.com/smithay/wayland-rs' CARGO_PKG_RUST_VERSION=1.59 CARGO_PKG_VERSION=0.1.1 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=1 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/<<PKGBUILDDIR>>/target/debug/deps:/usr/lib' OUT_DIR=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/build/wayland-backend-25412c02171791f3/out rustc --crate-name wayland_backend --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=9b41a18bbb70fa48 -C extra-filename=-9b41a18bbb70fa48 --out-dir /<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/<<PKGBUILDDIR>>/target/debug/deps --extern downcast_rs=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libdowncast_rs-70169c4a8a321adb.rmeta --extern io_lifetimes=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libio_lifetimes-229e7beedff98663.rmeta --extern nix=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libnix-d06b1ac03cad7931.rmeta --extern scoped_tls=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libscoped_tls-a04230133b0ac9fe.rmeta --extern smallvec=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libsmallvec-28e835236b5eb436.rmeta --extern wayland_sys=/<<PKGBUILDDIR>>/target/x86_64-unknown-linux-gnu/debug/deps/libwayland_sys-3dcf66d1ff8dbb08.rmeta -C debuginfo=2 --cap-lints warn -C linker=x86_64-linux-gnu-gcc -C link-arg=-Wl,-z,relro --remap-path-prefix /<<PKGBUILDDIR>>=/usr/share/cargo/registry/wayland-backend-0.1.1 --remap-path-prefix /<<PKGBUILDDIR>>/debian/cargo_registry=/usr/share/cargo/registry`
error[E0277]: `*const i8` cannot be shared between threads safely
   --> src/core_interfaces.rs:10:34
    |
10  | pub static WL_DISPLAY_INTERFACE: Interface = Interface {
    |                                  ^^^^^^^^^ `*const i8` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const i8`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const wl_message` cannot be shared between threads safely
   --> src/core_interfaces.rs:10:34
    |
10  | pub static WL_DISPLAY_INTERFACE: Interface = Interface {
    |                                  ^^^^^^^^^ `*const wl_message` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const wl_message`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const i8` cannot be shared between threads safely
   --> src/core_interfaces.rs:57:35
    |
57  | pub static WL_REGISTRY_INTERFACE: Interface = Interface {
    |                                   ^^^^^^^^^ `*const i8` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const i8`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const wl_message` cannot be shared between threads safely
   --> src/core_interfaces.rs:57:35
    |
57  | pub static WL_REGISTRY_INTERFACE: Interface = Interface {
    |                                   ^^^^^^^^^ `*const wl_message` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const wl_message`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const i8` cannot be shared between threads safely
   --> src/core_interfaces.rs:95:35
    |
95  | pub static WL_CALLBACK_INTERFACE: Interface = Interface {
    |                                   ^^^^^^^^^ `*const i8` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const i8`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const wl_message` cannot be shared between threads safely
   --> src/core_interfaces.rs:95:35
    |
95  | pub static WL_CALLBACK_INTERFACE: Interface = Interface {
    |                                   ^^^^^^^^^ `*const wl_message` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const wl_message`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const i8` cannot be shared between threads safely
   --> src/protocol.rs:180:33
    |
180 | pub static ANONYMOUS_INTERFACE: Interface =
    |                                 ^^^^^^^^^ `*const i8` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const i8`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

error[E0277]: `*const wl_message` cannot be shared between threads safely
   --> src/protocol.rs:180:33
    |
180 | pub static ANONYMOUS_INTERFACE: Interface =
    |                                 ^^^^^^^^^ `*const wl_message` cannot be shared between threads safely
    |
    = help: within `Interface`, the trait `Sync` is not implemented for `*const wl_message`
    = note: required because it appears within the type `wl_interface`
    = note: required because it appears within the type `&'static wl_interface`
    = note: required because it appears within the type `Option<&'static wl_interface>`
note: required because it appears within the type `Interface`
   --> src/protocol.rs:140:12
    |
140 | pub struct Interface {
    |            ^^^^^^^^^
    = note: shared static variables must have a type that implements `Sync`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `wayland-backend` due to 8 previous errors


```
Do I need a newer io-lifetimes ?

**Comment by kchibisov** [comment]
wayland-backend won't work with 0.29, you need 0.30.

**Comment by werdahias** [comment]
Ok, thanks. I'll update then
