### ISSUE TITLE
generate_c_interfaces not found but mentioned in documentation

### ISSUE THREAD

**Issue by gynther-k** [Smithay/wayland-rs#302]
The code below compiles successfully with wayland-scanner 0.21.*  .
However, it doesnt work with wayland-scanner 0.25.* and gives the error below.

**Cargo.toml**
```
[build-dependencies]
bindgen = "0.53.*"
meson = { version = "1.0", optional = true }
wayland-scanner = "0.25.*"
# For building optional dependencies
pkg-config = "0.3.*"

```
**Code**
```
        wayland_scanner::generate_c_code(
            protocol.0,
            output_dir.join(format!("{}_client_api.rs", protocol.1)),
            wayland_scanner::Side::Client
        );
        wayland_scanner::generate_c_interfaces(
            protocol.0,
            output_dir.join(format!("{}_interfaces.rs", protocol.1))
        );        	

```
**cargo build error**
```
error[E0425]: cannot find function `generate_c_code` in crate `wayland_scanner`
   --> build.rs:204:26
    |
204 |         wayland_scanner::generate_c_code(
    |                          ^^^^^^^^^^^^^^^ help: a function with a similar name exists: `generate_code`

error[E0425]: cannot find function `generate_c_interfaces` in crate `wayland_scanner`
   --> build.rs:209:26
    |
209 |         wayland_scanner::generate_c_interfaces(
    |                          ^^^^^^^^^^^^^^^^^^^^^ not found in `wayland_scanner`

```
How should I change my code? And why is generate_c_interfaces still mentioned here?
https://smithay.github.io/wayland-rs/wayland_scanner/

**Comment by vberger** [comment]
Indeed, this part of the documentation is outdated. There is now a single function to call : [`generate_code`](https://smithay.github.io/wayland-rs/wayland_scanner/fn.generate_code.html).

**Comment by gynther-k** [comment]
But before `generate_c_interfaces ` took only two arguments protocol and target. So now i should change it to `generate_code ` and also provide client or server side? Does it matter which one?

**Comment by vberger** [comment]
It depends whether you are generating code for use in a client wayland application (if you use `wayland-client`) or a wayland compositor (if you use `wayland-server`). You need to generate the one matching your need.
