### ISSUE TITLE
wayland-backend test fails to build since #731

### ISSUE THREAD

**Issue by jamessan** [Smithay/wayland-rs#782]
Since #731, in particular 06703518717675293228e7f9b0d60360723dd8ce, `cargo test -p wayland-backend --features server_system` fails to build:

```
error[E0433]: failed to resolve: could not find `client` in `sys`
   --> wayland-backend/tests/rs_sys_impls.rs:155:17
    |
155 |             dyn client::ObjectData: std::fmt::Debug, downcast_rs::DowncastSync
    |                 ^^^^^^ could not find `client` in `sys`
    |
note: found an item that was configured out
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:39:9
    |
39  | pub mod client;
    |         ^^^^^^
note: the item is gated here
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:37:1
    |
37  | #[cfg(any(test, feature = "client_system"))]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider importing this module
    |
151 +     use wayland_backend::client;
    |

error[E0433]: failed to resolve: could not find `client` in `sys`
   --> wayland-backend/tests/rs_sys_impls.rs:160:13
    |
160 |             client::ObjectId: std::fmt::Debug,
    |             ^^^^^^ could not find `client` in `sys`
    |
note: found an item that was configured out
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:39:9
    |
39  | pub mod client;
    |         ^^^^^^
note: the item is gated here
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:37:1
    |
37  | #[cfg(any(test, feature = "client_system"))]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider importing this module
    |
151 +     use wayland_backend::client;
    |

error[E0433]: failed to resolve: could not find `client` in `sys`
   --> wayland-backend/tests/rs_sys_impls.rs:170:22
    |
170 |         assert_impl!(client::Backend: Send, Sync, std::fmt::Debug);
    |                      ^^^^^^ could not find `client` in `sys`
    |
note: found an item that was configured out
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:39:9
    |
39  | pub mod client;
    |         ^^^^^^
note: the item is gated here
   --> /home/jamessan/src/github.com/wayland-rs/wayland-backend/src/sys/mod.rs:37:1
    |
37  | #[cfg(any(test, feature = "client_system"))]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider importing this module
    |
151 +     use wayland_backend::client;
    |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `wayland-backend` (test "rs_sys_impls") due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0308]: mismatched types
   --> wayland-backend/src/sys/mod.rs:115:63
    |
115 |         unsafe { self.backend.manage_object(interface, proxy, data) }
    |                               -------------                   ^^^^ expected trait `sys::client::ObjectData`, found trait `rs::client::ObjectData`
    |                               |
    |                               arguments to this method are incorrect
    |
    = note: expected struct `std::sync::Arc<(dyn sys::client::ObjectData + 'static)>`
               found struct `std::sync::Arc<(dyn rs::client::ObjectData + 'static)>`
note: method defined here
   --> wayland-backend/src/sys/client_impl/mod.rs:765:19
    |
765 |     pub unsafe fn manage_object(
    |                   ^^^^^^^^^^^^^
...
769 |         data: Arc<dyn ObjectData>,
    |         -------------------------

error[E0308]: mismatched types
   --> wayland-backend/src/sys/mod.rs:115:18
    |
114 |     ) -> ObjectId {
    |          -------- expected `rs::client::ObjectId` because of return type
115 |         unsafe { self.backend.manage_object(interface, proxy, data) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `rs::client::ObjectId`, found `sys::client::ObjectId`
    |
    = note: `sys::client::ObjectId` and `rs::client::ObjectId` have similar names, but are actually distinct types
note: `sys::client::ObjectId` is defined in module `crate::sys::client` of the current crate
   --> wayland-backend/src/sys/../client_api.rs:75:1
    |
75  | pub struct ObjectId {
    | ^^^^^^^^^^^^^^^^^^^
note: `rs::client::ObjectId` is defined in module `crate::rs::client` of the current crate
   --> wayland-backend/src/rs/../client_api.rs:75:1
    |
75  | pub struct ObjectId {
    | ^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `wayland-backend` (lib test) due to 2 previous errors
```

I'm not sure why this doesn't show up when running `cargo test --workspace --exclude wayland-tests --features server_system`.

I'm trying to update Debian's wayland-rs packages and running into this issue.
